site_name: "GrandPy"
site_author: "Andreas Wei√ü"
repo_url: "https://git.uni-regensburg.de/se24/g03/grandpy"
repo_name: GitLab

theme:
  name: null
  custom_dir: 'mkdocs_docskimmer'
  include_search_page: true
  search_index_only: false
  static_templates:
    - 404.html

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            merge_init_into_class: true
            modernize_annotations: true
            signature_crossrefs: true
            show_source: true
            separate_signature: true
            members_order: source
            extra:
              show_signature: false
            filters:
              - "!^_"


nav:
  - Home: index.md
  - Getting startet: notebooks/notebook_00_getting_started.ipynb
  - Tutorials: tutorials/tutorials.md
  - API:
      - GrandPy: api/core_grandpy.md
      - Load: api/load.md
      - Plots: api/plot.md
      - Processing: api/processing.md
      - Lfc: api/lfc.md
      - Differential Expression: api/diffexp.md
      - Modeling: api/modeling.md
      - Utils: api/utils.md
      - Analysis_tool: api/analysis_tool.md
      - Plot_tool: api/plot_tool.md
      - Slot_tool: api/slot_tool.md



extra:
  version: 0.4.0
  logo: logo/grandPy_hex_logo.png
  favicon: logo/grandPy_hex_logo.ico




extra_css:
  - css/custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
